#include <stdio.h>
#include <stdlib.h>

#define ERR(...) fprintf(stderr, __VA_ARGS__)

int main (int argc, char **argv)
{
    int ch, i;

    if (argc != 2) {
        ERR("usage: %s tag < input > output\n", argv[0]);
        return -1;
    }

    printf("/* Automatically generated by BIN2C, G.Vanem 1995 */\n");
    printf("const char %s[] = {\n", argv[1]);

    for (i = 0, ch = fgetc(stdin); ch != EOF; i++, ch = fgetc(stdin))
    {
        if (i == 0)
            printf("    ");
        else if (i % 12 == 0)
            printf("\n    ");

        printf("0x%02X,", ch);
    }
    printf("\n};\n");
    printf("const int %s_len = %d;\n", argv[1], i);

    return 0;
}
